#!/usr/bin/env ruby

$LOAD_PATH << './'
require 'optparse'
require 'bundler'

options = OptionParser.new do |opts|
  opts.banner = <<-EOF
Usage:
  agent_installer install [options]
EOF

  opts.on("-v", "--verbose", "Run verbosely") do
    NewRelic::Plugin::Config.config.newrelic['verbose'] = 1
  end

  opts.on("-l", "--license LICENSE_KEY", "Your NewRelic account License Key") do | license_key |
    $license_key = license_key
  end

  opts.on('-f', '--force', 'Force config file overwrite') do 
    $force_overwrite = true
  end

  opts.on("-h", "--help") do
    puts opts
    if File.basename($0) == File.basename(__FILE__)
      exit 0
    end
  end
end

args = options.parse!(ARGV)
if args.first == 'install'
  config_file = File.read(File.expand_path("../config/newrelic_plugin.yml.template", __FILE__))
  if $license_key
    config_file.gsub!("YOUR_LICENSE_KEY_HERE", $license_key)
  end
  config_path = 'config/newrelic_plugin.yml'
  FileUtils.mkdir_p "config"
  if FileTest.exist?(config_path) and !$force_overwrite
    puts "Agent config file #{File.expand_path(config_path)} already exists. Use -f option to force overwrite."
  else
    File.open(config_path, "w") do | io |
      io.write(config_file)
    end
    puts "Saved agent config file #{File.expand_path(config_path)}"
  end
  system('bundle install')
else
  puts options
end

